//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eforaxis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ventas
    {
        public int id_venta { get; set; }
        public string estado { get; set; }
        public string productos { get; set; }
        public decimal total { get; set; }
        public int id_usuario { get; set; }
        public string metodo { get; set; }
    }
}
